"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15j8t3mVsIjXkNA5EitjMasoCo4WuUw7Z
"""


import streamlit as st
import pandas as pd
import altair as alt

# Define conceptos here so it is accessible to all parts of the script
conceptos = ['FC_DEFINICION', 'FC_ROLES', 'FC_TECNOLOGIA', 'FC_APLICACION', 'FC_BENEFICIOS']

# Cargar datos
contenido_df = pd.read_csv("contenido_tematico.csv")
estudiantes_df = pd.read_csv("estudiantes.csv")

# Mapeo de niveles de conocimiento a niveles de dificultad
nivel_map = {
    0.25: "Básico",
    0.55: "Intermedio",
    0.85: "Avanzado"
}

# Función para obtener contenido personalizado
def obtener_contenido(estudiante_id, concepto):
    estudiante = estudiantes_df[estudiantes_df['id'] == estudiante_id]
    if estudiante.empty:
        return "Estudiante no encontrado."

    nivel_conocimiento = estudiante[concepto].iloc[0]
    nivel_dificultad = nivel_map.get(nivel_conocimiento, "Básico")

    contenido = contenido_df[
        (contenido_df['ID_Concepto'] == concepto) &
        (contenido_df['NivelDificultad'] == nivel_dificultad)
    ]

    if contenido.empty:
        return f"No hay contenido disponible para {concepto} en nivel {nivel_dificultad}."

    texto = contenido['TextoContenido'].iloc[0]
    ejemplos = contenido['Ejemplos Prácticos'].iloc[0]
    return f"**Contenido ({nivel_dificultad})**: {texto}\n\n**Ejemplos Prácticos**:\n{ejemplos}"

# Interfaz en Streamlit
st.title("Sistema de Aprendizaje Personalizado - Flipped Classroom")

# Selección del estudiante
estudiante_id = st.number_input("Ingresa tu ID de estudiante", min_value=1, step=1)
if estudiante_id:
    estudiante = estudiantes_df[estudiantes_df['id'] == estudiante_id]
    if not estudiante.empty:
        st.write(f"**Nombre del estudiante**: {estudiante['nombre'].iloc[0]}")

        # Mostrar nivel de conocimiento actual
        st.subheader("Tu nivel de conocimiento actual:")
        niveles = []
        for concepto in conceptos:
            nivel_num = estudiante[concepto].iloc[0]
            nivel_texto = nivel_map.get(nivel_num, "Desconocido")
            niveles.append({"Concepto": concepto, "Nivel": nivel_texto, "Valor": nivel_num})
            # Eliminado: st.write(f"{concepto}: {nivel_texto}")  # No mostrar la lista de texto

        # Convertir a DataFrame para Altair
        niveles_df = pd.DataFrame(niveles)

        # Crear gráfico de barras con Altair
        chart = alt.Chart(niveles_df).mark_bar().encode(
            x=alt.X('Concepto:N', title='Concepto', sort=conceptos),
            y=alt.Y('Valor:Q', title='Nivel de Conocimiento', scale=alt.Scale(domain=[0, 1])),
            color=alt.Color('Nivel:N', scale=alt.Scale(domain=['Básico', 'Intermedio', 'Avanzado'], range=['#ff9999', '#66b3ff', '#99ff99'])),
            tooltip=['Concepto', 'Nivel', 'Valor']
        ).properties(
            width='container',
            height=300,
            title=alt.TitleParams(
                text='Niveles de Conocimiento por Concepto',
                anchor='middle',
                offset=20,
                fontSize=16
            )
        ).configure_title(
            dy=-10
        )

        # Mostrar el gráfico con espacio adicional
        st.markdown("---")
        st.altair_chart(chart, use_container_width=True)
        st.markdown("---")

        # Mostrar contenido personalizado
        st.subheader("Contenido personalizado para ti:")
        for concepto in conceptos:
            with st.expander(f"Contenido para {concepto}"):
                st.markdown(obtener_contenido(estudiante_id, concepto))
    else:
        st.error("ID de estudiante no encontrado.")

# Opcional: Formulario para actualizar nivel de conocimiento
st.subheader("Actualizar nivel de conocimiento")
with st.form("actualizar_conocimiento"):
    estudiante_id_update = st.number_input("ID del estudiante", min_value=1, step=1)
    concepto_update = st.selectbox("Concepto", conceptos)
    nuevo_nivel = st.selectbox("Nuevo nivel", [0.25, 0.55, 0.85], format_func=lambda x: nivel_map[x])
    submit = st.form_submit_button("Actualizar")

    if submit:
        idx = estudiantes_df[estudiantes_df['id'] == estudiante_id_update].index
        if not idx.empty:
            estudiantes_df.loc[idx, concepto_update] = nuevo_nivel
            estudiantes_df.to_csv("estudiantes.csv", index=False)
            st.success("Nivel de conocimiento actualizado.")
        else:
            st.error("Estudiante no encontrado.")
